name: build image

on:
  push:
    branches:
      - master

env:
  scu_key: xxxxxxxxxxxxxxxxxxxx

defaults:
  run:
    shell: bash
    
jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: clone project
        continue-on-error: false
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY .
      
      - name: build
        run: |
          docker build -t trojan . 
      
      - name: test
        run: |
          docker create --name trojan-server -v /var/log/trojan/:/var/log/trojan/ -p 443:443 --restart always trojan -c /etc/trojan/trojan-server.json
          docker start trojan-server
          docker ps